---
title: "Exploring Linear model Parameters"
author: "Fabien KON-SUN-TACK"
date: "5/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'results/20210419/')
```

```{r eval=T, echo=T,  results="verbatim"}

if (!exists("mreadRDS")) {
  mreadRDS = memoise::memoise(function(...) {print("reading..."); ret=readRDS(...); print("done."); return(ret)})
}
s = mreadRDS("../../data/study_hadaca_epic.rds")
d = s$data
d = na.omit(d)
pf = s$platform
e = s$exp_grp
head(d)
head(pf[,1:6])
table(substr(e$cond,1,4))
nb_probes = nrow(d)
```

```{r}
e$cond
levels(e$cond)
levels(e$cond)[levels(e$cond)=="WTws_rep6"] = "C_serum"
levels(e$cond)[levels(e$cond)=="WTwo_rep6"] = "D_woser"
e = e[e$cond=="C_serum" | e$cond=="D_woser",]
e$cond = factor(e$cond)
e$cond = relevel(e$cond, "C_serum")
e$cond
idx_C = colnames(d)[17:24]
idx_D = colnames(d)[25:32]
d = d[,c(idx_C,idx_D)]
head(d)
```

```{r}
prefix = "ewas_mean"
pval_tresh = 10^-2
prefix2 = paste0(prefix, "_", pval_tresh)
region_file = paste0("dmr_", prefix2, ".regions.bed.gz"   )
if (file.exists(region_file)) {
  region = read.table(gzfile(region_file), comment="@", header=F, stringsAsFactors=FALSE)
} else {
  warning(paste0("region_file ", region_file, " does not exist. Have to fix it! "))
  return(NULL)
}
```

```{r test, eval=T, results="verbatim"}
apply_func =  apply
apply_func =  epimedtools::monitored_apply
model = apply_func(d[1:100,],1, function(l){
  #print(l)
  #l = d[rownames(d)[1],]
  data = e[colnames(d),]
  data$meth = l
  m_DC = lm(meth~cond, data)
  boxplot(meth~cond, data)
  abline(h=mean(data[idx_C,3]), col=4)
  abline(h=mean(data[idx_D,3]), col=2)
  abline(h=m_DC$coef[[1]], lty=2)
  abline(h=m_DC$coef[[1]]+m_DC$coef[[2]], lty=3)
  fstat_DC = summary(m_DC)$fstatistic
  pval_DC =  1 - pf(fstat_DC[1], fstat_DC[2], fstat_DC[3])
  
  ret = c(
    pval = pval_DC,
    intercept = m_DC$coef[[1]],
    coef = m_DC$coef[[1]] + m_DC$coef[[2]]
  )
  return(ret)
}
)
results = data.frame(t(model))
region = cbind(region, model)
```
## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
