---
title: "Epic data from Hadaca"
subtitle: "PCA"
author: "Florent Chuffart"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---


```{r, echo=FALSE, eval=TRUE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="hide")
```

```{r label="loading data"}
if (!exists("mreadRDS")) {mreadRDS = memoise::memoise(readRDS)}
s = mreadRDS("../../data/study_hadaca_epic.rds")
```



# Design 

```{r exp_grp, echo=TRUE, results="verbatim"}
table(substr(s$exp_grp$cond, 1, 4))

```



# PCA

```{r fig.width=9, fig.height=9, eval=TRUE, label="PCA"}
if (!exists("pca")) {
  data = s$data
  dim(data)
  # filtering...
  idx = apply(is.na(data), 1, any)
  sum(idx)
  data = data[!idx,]
  idx = apply(data, 1, function (l){
    length(unique(l)) == 1
  })
  sum(idx)
  data = data[!idx,]
  dim(data)
  set.seed(1)
  pca = prcomp(t(data[sample(1:nrow(data), 1000),]), scale=TRUE)  
}
  
v = pca$sdev * pca$sdev
p = v / sum(v) * 100
layout(matrix(1:4,2, byrow=FALSE), respect=TRUE)
barplot(p)
i=3
j=2
plot(pca$x[,i], pca$x[,j], xlab=paste0("PC", i, "(", signif(p[i], 3), "%)"), ylab=paste0("PC", j, "(", signif(p[j], 3), "%)"), col=as.numeric(s$exp_grp[rownames(pca$x),]$cond), pch=16)
text(pca$x[,i], pca$x[,j], rownames(pca$x))
i=1
j=3
plot(pca$x[,i], pca$x[,j], xlab=paste0("PC", i, "(", signif(p[i], 3), "%)"), ylab=paste0("PC", j, "(", signif(p[j], 3), "%)"), col=as.numeric(s$exp_grp[rownames(pca$x),]$cond), pch=16)
text(pca$x[,i], pca$x[,j], rownames(pca$x))
i=1
j=2
plot(pca$x[,i], pca$x[,j], xlab=paste0("PC", i, "(", signif(p[i], 3), "%)"), ylab=paste0("PC", j, "(", signif(p[j], 3), "%)"), col=as.numeric(s$exp_grp[rownames(pca$x),]$cond), pch=16)
text(pca$x[,i], pca$x[,j], rownames(pca$x))
```



# Session Information

```{r results="verbatim"}
sessionInfo()
```

