---
title: "Premiers essais sur le jeu de données"
author: "Fabien KON-SUN-TACK"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---

```{r, echo=FALSE, eval=TRUE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="hide")
```

```{r loading_data}
if (!exists("mreadRDS")) {mreadRDS = memoise::memoise(readRDS)}
s = mreadRDS("../../data/study_hadaca_epic.rds")
NAS = apply(is.na(s$data), 2, which)
NAS[1]
d = s$data
d = na.omit(d)
e = s$exp_grp
e$cond = substr(s$exp_grp$cond, 1, 4)

nb_probes = nrow(d)
```

# Design 

```{r exp_grp, echo=TRUE, results="verbatim"}
table(e$cond)
print("4 conditions, 8 réplicats par condition")
```

## Data
```{r echo=TRUE, results="verbatim", label = "Data Description"}
idx_A = colnames(d)[01:08]
idx_B = colnames(d)[09:16]
idx_C = colnames(d)[17:24]
idx_D = colnames(d)[25:32]
print(head(d[,idx_A]))
print(head(d[,idx_B]))
print(head(d[,idx_C]))
print(head(d[,idx_D]))
```

## Graphs
```{r plot_data, echo=TRUE, fig.height=9}
layout(matrix(1:4, 2), respect=TRUE)
hist(d[,idx_A], main="Condition A: HCT116 double KO DNMT1-DNMT3")
hist(d[,idx_B], main="Condition B: HCT116 simple KO DNMT1")
hist(d[,idx_C], main="Condition C: HCT116 WT serum")
hist(d[,idx_D], main="Condition D: HCT116 WT serum deprivation 24h")
```

# Univariate Analysis

## Student tests

```{r ewas_mean, echo=TRUE, eval=TRUE, results="verbatim"}
apply_func =  apply
apply_func =  epimedtools::monitored_apply
if (!file.exists("ewas_mean.rds")) {
  ewas_mean =  apply_func(d[1:nb_probes,] , 1, function(l) {  
    # print(l)
    # l = d[1,]
    
    data =  e[colnames(d),]
    data$meth =  l
    m_AC =  lm(meth~cond, data[c(idx_A, idx_C),])
    m_BC =  lm(meth~cond, data[c(idx_B, idx_C),])
    m_DC =  lm(meth~cond, data[c(idx_D, idx_C),])
    
    fstat_AC =  summary(m_AC)$fstatistic
    fstat_BC =  summary(m_BC)$fstatistic
    fstat_DC =  summary(m_DC)$fstatistic

    pval_AC =  1 - pf(fstat_AC[1], fstat_AC[2], fstat_AC[3]) # anova(m_AC)[1,5]
    pval_BC =  1 - pf(fstat_BC[1], fstat_BC[2], fstat_BC[3]) # anova(m_BC)[1,5]
    pval_DC =  1 - pf(fstat_DC[1], fstat_DC[2], fstat_DC[3]) # anova(m_DC)[1,5]

    beta_AC =  m_AC$coef[[2]]
    beta_BC =  m_BC$coef[[2]]
    beta_DC =  m_DC$coef[[2]]

    ret <-  c(
      pval_AC = pval_AC,
      pval_BC = pval_BC,
      pval_DC = pval_DC,
      beta_AC = beta_AC,
      beta_BC = beta_BC,
      beta_DC = beta_DC,
      NULL
    )
    return(ret)
    }
  )
  ewas_mean = data.frame(t(ewas_mean))
  head(ewas_mean)
  saveRDS(ewas_mean, "ewas_mean.rds")
  }
  ewas_mean = readRDS("ewas_mean.rds")

```


## Fisher tests (variance)

```{r ewas_var, echo=TRUE, eval=TRUE, results="verbatim"}
if (!file.exists("ewas_var.rds")) {
  ewas_var <- apply_func(d[1:nb_probes,] , 1, function(l) {  
    # print(l)
    # l = d[1,]
  
    vtest_AC = var.test(l[idx_A],l[idx_C])
    vtest_BC = var.test(l[idx_B],l[idx_C])
    vtest_DC = var.test(l[idx_D],l[idx_C])

    pval_AC = vtest_AC$p.value 
    pval_BC = vtest_BC$p.value 
    pval_DC = vtest_DC$p.value 
    beta_AC = log2(vtest_AC$estimate[[1]])
    beta_BC = log2(vtest_BC$estimate[[1]])
    beta_DC = log2(vtest_DC$estimate[[1]])

    ret = c(
      pval_AC = pval_AC,
      pval_BC = pval_BC,
      pval_DC = pval_DC,
      beta_AC = beta_AC,
      beta_BC = beta_BC,
      beta_DC = beta_DC,
      NULL
    )
    return(ret)
    }
  )
  ewas_var = data.frame(t(ewas_var))
  head(ewas_var)
  saveRDS(ewas_var, "ewas_var.rds")
 }
 ewas_var = readRDS("ewas_var.rds")
```


```{r echo=TRUE, results="verbatim"}
head(ewas_mean)
head(ewas_var)
```

# FDR BH

```{r fdr_bh, echo=TRUE, eval=TRUE, results="verbatim"}
ewas_mean$padj_AC = p.adjust(ewas_mean$pval_AC, method="BH")
ewas_mean$padj_BC = p.adjust(ewas_mean$pval_BC, method="BH")
ewas_mean$padj_DC = p.adjust(ewas_mean$pval_DC, method="BH")
ewas_var$padj_AC = p.adjust(ewas_var$pval_AC, method="BH")
ewas_var$padj_BC = p.adjust(ewas_var$pval_BC, method="BH")
ewas_var$padj_DC = p.adjust(ewas_var$pval_DC, method="BH")
```

```{r exo_fdr}
layout(matrix(1:2,1), respect=TRUE)
plot(-log10(ewas_mean$padj_AC), -log10(ewas_mean$pval_AC))
abline(a=0, b=1)
abline(v=-log10(0.05), col=2, lty=2)

plot(-log10(ewas_mean$padj_AC), -log10(ewas_mean$pval_AC), xlim=c(0, 2), ylim=c(0, 2), )
abline(a=0, b=1)
abline(v=-log10(0.05), col=2, lty=2)
abline(h=-log10(0.05), col=4, lty=2)

plot(-log10(ewas_mean$padj_DC), -log10(ewas_mean$pval_DC))
abline(a=0, b=1)
abline(v=-log10(0.05), col=2, lty=2)

plot(-log10(ewas_mean$padj_DC), -log10(ewas_mean$pval_DC), xlim=c(0, 2), ylim=c(0, 2), )
abline(a=0, b=1)
abline(v=-log10(0.05), col=2, lty=2)
abline(h=-log10(0.05), col=4, lty=2)

plot(-log10(ewas_mean$padj_BC), -log10(ewas_mean$pval_BC))
abline(a=0, b=1)
abline(v=-log10(0.05), col=2, lty=2)

plot(-log10(ewas_mean$padj_BC), -log10(ewas_mean$pval_BC), xlim=c(0, 2), ylim=c(0, 2), )
abline(a=0, b=1)
abline(v=-log10(0.05), col=2, lty=2)
abline(h=-log10(0.05), col=4, lty=2)

FDR = function (x, FDR=0.05) {
    x <- sort(na.omit(x))
    N = length(x)
    i = 1
    while (N * x[i]/i < FDR & i <= N) {
      i = i + 1
    }
    if (i == 1) {
      return(NA)      
    } else {
      return(x[i - 1])
    }
}

abline(h=-log10(FDR(ewas_mean$pval_AC)), col=3, lty=2)
```

# Volcano Plot
```{r echo=T,eval=T,results="hold",label="Volcano plotting data"}
layout(matrix(1:2,1), respect=TRUE)
plot(ewas_mean$beta_AC, -log10(ewas_mean$pval_AC), xlab="beta", ylab="-log10(pval)", main="cond A vs. cond C, mean")
plot(ewas_mean$beta_AC, -log10(ewas_mean$padj_AC), xlab="beta", ylab="-log10(padj)", main="cond A vs. cond C, mean")
plot(ewas_mean$beta_BC, -log10(ewas_mean$pval_BC), xlab="beta", ylab="-log10(pval)", main="cond B vs. cond C, mean")
plot(ewas_mean$beta_BC, -log10(ewas_mean$padj_BC), xlab="beta", ylab="-log10(padj)", main="cond B vs. cond C, mean")
plot(ewas_mean$beta_DC, -log10(ewas_mean$pval_DC), xlab="beta", ylab="-log10(pval)", main="cond D vs. cond C, mean")
plot(ewas_mean$beta_DC, -log10(ewas_mean$padj_DC), xlab="beta", ylab="-log10(padj)", main="cond D vs. cond C, mean")
plot( ewas_var$beta_AC, -log10( ewas_var$pval_AC), xlab="beta", ylab="-log10(pval)", main="cond A vs. cond C, _var")
plot( ewas_var$beta_AC, -log10( ewas_var$padj_AC), xlab="beta", ylab="-log10(padj)", main="cond A vs. cond C, _var")
plot( ewas_var$beta_BC, -log10( ewas_var$pval_BC), xlab="beta", ylab="-log10(pval)", main="cond B vs. cond C, _var")
plot( ewas_var$beta_BC, -log10( ewas_var$padj_BC), xlab="beta", ylab="-log10(padj)", main="cond B vs. cond C, _var")
plot( ewas_var$beta_DC, -log10( ewas_var$pval_DC), xlab="beta", ylab="-log10(pval)", main="cond D vs. cond C, _var")
plot( ewas_var$beta_DC, -log10( ewas_var$padj_DC), xlab="beta", ylab="-log10(padj)", main="cond D vs. cond C, _var")


```
```{r echo=T, eval=T, results="verbatim"}

stats <-ewas_mean[ewas_mean[,1] < 0.05 | ewas_mean[,2] < 0.05 | ewas_mean[,3] < 0.05,]
negAC <- data.frame(stats[stats[,4] < 0, 4])
(nrow(negAC)/nrow(stats)) * 100
negBC <- data.frame(stats[stats[,5] < 0, 5])
(nrow(negBC)/nrow(stats)) * 100
negDC <- data.frame(stats[stats[,6] < 0, 6])
(nrow(negDC)/nrow(stats)) * 100
posAC <- data.frame(stats[stats[,4] > 0, 4])
(nrow(posAC)/nrow(stats)) * 100
posBC <- data.frame(stats[stats[,5] > 0, 5])
(nrow(posBC)/nrow(stats)) * 100
posDC <- data.frame(stats[stats[,6] > 0, 6])
(nrow(posDC)/nrow(stats)) * 100
vars <-ewas_var[ewas_var[,1] < 0.05 | ewas_var[,2] < 0.05 | ewas_var[,3] < 0.05,]
negAC <- data.frame(stats[stats[,4] < 0, 4])
(nrow(negAC)/nrow(stats)) * 100
negBC <- data.frame(stats[stats[,5] < 0, 5])
(nrow(negBC)/nrow(stats)) * 100
negDC <- data.frame(stats[stats[,6] < 0, 6])
(nrow(negDC)/nrow(stats)) * 100
posAC <- data.frame(stats[stats[,4] > 0, 4])
(nrow(posAC)/nrow(stats)) * 100
posBC <- data.frame(stats[stats[,5] > 0, 5])
(nrow(posBC)/nrow(stats)) * 100
posDC <- data.frame(stats[stats[,6] > 0, 6])
(nrow(posDC)/nrow(stats)) * 100
```

```{r}
layout(matrix(1:2,1), respect=TRUE)

plot(ewas_mean$beta_DC, ewas_var$beta_DC)
plot(-log10(ewas_mean$pval_DC), -log10(ewas_var$pval_DC))

plot(ewas_mean$beta_BC, ewas_var$beta_BC)
plot(-log10(ewas_mean$pval_BC), -log10(ewas_var$pval_BC))

plot(ewas_mean$beta_AC, ewas_var$beta_AC)
plot(-log10(ewas_mean$pval_AC), -log10(ewas_var$pval_AC))


```

# ```{manhattan r echo=T, eval=T, results="verbatim"}
# EWAS_plots(ewas_mean, plot_Man = T, save_name = "ewas_mean")
# 
# ```


# Session Information

```{r results="verbatim"}
sessionInfo()
```

