---
title: "Summary"
author: "Fabien KON-SUN-TACK"
date: "6/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'results/20210419/')
library(reshape2)
library(ggplot2)
library(dplyr)
library(tidyr)
library(epimedtools)
apply_func =  apply
apply_func =  epimedtools::monitored_apply

prefix = "ewas_mean"
prefix_var = "ewas_var"

```

# EWAS
## Loading Data
```{r}
if (!exists("mreadRDS")) {
  mreadRDS = memoise::memoise(function(...) {print("reading..."); ret=readRDS(...); print("done."); return(ret)})
}
s = mreadRDS("../../data/study_hadaca_epic.rds")
d = s$data
sum(is.na(d))
dim(d)
d = na.omit(d)
dim(d)
sum(is.na(d))
e = s$exp_grp
pf = s$platform
replicates = c("C1","C2","C3","C4","C5","C6","C7","C8","D1","D2","D3","D4","D5","D6","D7","D8")
nb_probes = nrow(d)
```

## Design
```{r exp_grp, echo=TRUE, results="verbatim"}
table(e$cond)
levels(e$cond)[levels(e$cond)=="DbKO_rep1"] = "A_dbko"
levels(e$cond)[levels(e$cond)=="D1KO_rep3"] = "B_doko"
levels(e$cond)[levels(e$cond)=="WTws_rep6"] = "C_serum"
levels(e$cond)[levels(e$cond)=="WTwo_rep6"] = "D_woser"
e$cond = factor(e$cond,levels=c("A_dbko","B_doko","C_serum","D_woser"))
table(e$cond)
e$cond

idx_A = colnames(d)[01:08]
idx_B = colnames(d)[09:16]
idx_C = colnames(d)[17:24]
idx_D = colnames(d)[25:32]
print(head(d[,idx_A]))
print(head(d[,idx_B]))
print(head(d[,idx_C]))
print(head(d[,idx_D]))

# testing
tmp_probes = c("cg21020221",  "cg06619462", "cg18748898")

d = d[,c(idx_C,idx_D)]
e = e[e$cond=="C_serum"|e$cond=="D_woser",]
e$cond = factor(e$cond,levels=c("C_serum","D_woser"))
```

## EWAS_mean

```{r ewas_mean, echo=F, eval=TRUE, results="verbatim"}
if (!file.exists(paste0(prefix,".rds"))) {
  ewas_mean =  apply_func(d[1:nb_probes,] , 1, function(l) {  
    # print(l)
    # l = d[1,]
    
    data =  e[colnames(d),]
    data$meth =  l
    m_AC =  lm(meth~cond, data[c(idx_A, idx_C),])
    m_BC =  lm(meth~cond, data[c(idx_B, idx_C),])
    m_DC =  lm(meth~cond, data[c(idx_D, idx_C),])
    
    fstat_AC =  summary(m_AC)$fstatistic
    fstat_BC =  summary(m_BC)$fstatistic
    fstat_DC =  summary(m_DC)$fstatistic

    pval_AC =  1 - pf(fstat_AC[1], fstat_AC[2], fstat_AC[3]) # anova(m_AC)[1,5]
    pval_BC =  1 - pf(fstat_BC[1], fstat_BC[2], fstat_BC[3]) # anova(m_BC)[1,5]
    pval_DC =  1 - pf(fstat_DC[1], fstat_DC[2], fstat_DC[3]) # anova(m_DC)[1,5]

    beta_AC =  m_AC$coef[[2]]
    beta_BC =  m_BC$coef[[2]]
    beta_C = m_DC$coef[[1]]
    beta_D = m_DC$coef[[1]]+m_DC$coef[[2]]
    sd_A = sd(data[data$cond=="A_dbko",]$meth)
    sd_B = sd(data[data$cond=="B_doko",]$meth)
    sd_C = sd(data[data$cond=="C_serum",]$meth)
    sd_D = sd(data[data$cond=="D_woser",]$meth)

    ret <-  c(
      pval_AC = pval_AC,
      pval_BC = pval_BC,
      pval_DC = pval_DC,
      beta_AC = beta_AC,
      beta_BC = beta_BC,
      beta_C = beta_C,
      beta_D = beta_D,
      sd_A = sd_A,
      sd_B = sd_B,
      sd_C = sd_C,
      sd_D = sd_D,
      NULL
    )
    return(ret)
    }
  )
  ewas_mean = data.frame(t(ewas_mean))
  head(ewas_mean)
  saveRDS(ewas_mean, paste0(prefix,".rds"))
}

ewas_mean = mreadRDS(paste0(prefix,".rds"))
head(ewas_mean)
ewas_mean[tmp_probes,]
```

## EWAS_var

```{r ewas_var, echo=TRUE, eval=TRUE, results="verbatim"}
if (!file.exists("ewas_var.rds")) {
  ewas_var <- apply_func(d[1:nb_probes,] , 1, function(l) {  
    # print(l)
    # l = d[1,]
    data = e[colnames(d),]
    data$meth = l
    # vtest_AC = var.test(meth~cond,data[c(idx_A,idx_C),])
    # vtest_BC = var.test(meth~cond,data[c(idx_B,idx_C),])
    # vtest_DC = var.test(meth~cond,data[c(idx_D,idx_C),])
    vtest_AC = var.test(l[idx_A],l[idx_C])
    vtest_BC = var.test(l[idx_B],l[idx_C])
    vtest_DC = var.test(l[idx_D],l[idx_C])
    # vtest_AC = aov(meth~cond,data[c(idx_A,idx_C),])
    # vtest_BC = aov(meth~cond,data[c(idx_B,idx_C),])
    # vtest_DC = aov(meth~cond,data[c(idx_D,idx_C),])
    pval_AC = vtest_AC$p.value
    pval_BC = vtest_BC$p.value
    pval_DC = vtest_DC$p.value
    # pval_AC = anova(vtest_AC)[1,5]
    # pval_BC = anova(vtest_BC)[1,5] 
    # pval_DC = anova(vtest_DC)[1,5]
    beta_AC = vtest_AC$estimate[[1]]
    beta_BC = vtest_BC$estimate[[1]]
    beta_CD = vtest_DC$estimate[[1]]

    ret = c(
      pval_AC = pval_AC,
      pval_BC = pval_BC,
      pval_DC = pval_DC,
      beta_AC = beta_AC,
      beta_BC = beta_BC,
      beta_CD = beta_CD,
      NULL
    )
    return(ret)
    }
  )
  ewas_var = data.frame(t(ewas_var))
  head(ewas_var)
  saveRDS(ewas_var, "ewas_var.rds")
 }
 ewas_var = readRDS("ewas_var.rds")
```

# Comb-P

## Preparing Data
```{r}
ewas = ewas_mean[,c("beta_C","beta_D","pval_DC.value","sd_C","sd_D")]
colnames(ewas) = c("beta_C", "beta_D", "lpv","sd_C","sd_D")
ewas$lpv = -log10(ewas$lpv)
lpval = ewas[,"lpv"]
names(lpval) = rownames(ewas)

ewas_v = ewas_var[,c("beta_CD", "pval_DC")]
colnames(ewas_v) = c("beta", "lpv")
ewas_v$lpv = -log10(ewas_v$lpv)
lpval_v = ewas_v[,"lpv"]
names(lpval_v) = rownames(ewas_var)

```

```{r}
pval = 10^-lpval
# build and write bed file
bed = pf[rownames(ewas),c(1:3,5)] # Warning, here pf is global, it must be arg and indexed!!
head(bed)
bed$probes = names(pval)
bed$pval = pval
bed$beta_C = ewas[,"beta_C"]
bed$beta_D = ewas[,"beta_D"]
bed$sd_C = ewas[,"sd_C"]
bed$sd_D = ewas[,"sd_D"]
bed = cbind(bed,d[,c(idx_C,idx_D)])
bed = bed[,c(1:3,5,6:10,4,11:26)]
colnames(bed) = c("chrom", "start", "end", "probes", "pval", "beta_C","beta_D","sd_C","sd_D", "strand",replicates)

bed = na.omit(bed)
head(bed)
# write ewas res for combp
bed_ewas_filename = paste0("ewas4combp_", prefix,".bed")
bed[,1] = as.character(bed[,1])
bed = bed[order(bed[,1], bed[,2]),]
write.table(bed,file=bed_ewas_filename , sep="\t", quote=FALSE, row.names=FALSE, col.names=TRUE)
# bed = read.table(ewas_filename, sep="\t", header=TRUE)


pval_v = 10^-lpval_v
# build and write bed file
bed_var = pf[rownames(ewas_v),c(1:3,5)] # Warning, here pf is global, it must be arg and indexed!!
head(bed_var)
bed_var$probes = names(pval_v)
bed_var$pval = pval_v
bed_var$beta = ewas_v[,"beta"]
bed_var = cbind(bed_var,d[,c(idx_C,idx_D)])
bed_var = bed_var[,c(1:3,5:7,4,8:23)]

colnames(bed_var)[1] = "chrom"

bed_var = na.omit(bed_var)
head(bed_var)
# write ewas res for combp
bed_ewas_var_filename = paste0("ewas4combp_", prefix_var,".bed")
bed_var[,1] = as.character(bed_var[,1])
bed_var = bed_var[order(bed_var[,1], bed_var[,2]),]
write.table(bed_var,file=bed_ewas_var_filename , sep="\t", quote=FALSE, row.names=FALSE, col.names=TRUE)
# bed = read.table(ewas_filename, sep="\t", header=TRUE)


```

## Run Comb-P
```{r combp}
pval_tresh = 10^-3
prefix2 = paste0(prefix, "_", pval_tresh)
# Run comb-p, run!!
cmd = "comb-p"
arg = paste0("pipeline -c 5 --seed ", pval_tresh, " --dist 1000 -p dmr_", prefix2," --region-filter-p 0.05 --region-filter-n 2 ", bed_ewas_filename)
bed_ewas_florent = read.table("test/ewas4combp_study_hadaca_meth_raw.rds_model01.bed",comment="@",header=T)
arg_f = paste0("pipeline -c 5 --seed ", pval_tresh, " --dist 1000 -p dmr_", prefix2," --region-filter-p 0.05 --region-filter-n 2 ", bed_ewas_florent)
print(paste(cmd, arg))
system2(cmd, arg)

pval_tresh_var = 10^-2
prefix2_var = paste0(prefix_var, "_", pval_tresh_var)
# Run comb-p, run!!
cmd_var = "comb-p"
arg_var = paste0("pipeline -c 5 --seed ", pval_tresh_var, " --dist 1000 -p dmr_", prefix2_var," --region-filter-p 0.05 --region-filter-n 2 ", bed_ewas_var_filename)
print(paste(cmd_var, arg_var))
system2(cmd_var, arg_var)

```

## Comb-P Results

```{r results, eval=TRUE, results= "hold"}
# Read comb-p ewas input
bed_ewas = read.table(bed_ewas_filename, sep="\t",comment="@", header=TRUE)
rownames(bed_ewas) = bed_ewas$probes
head(bed_ewas)
dim(bed_ewas)

# Read comb-p outputs
probes_file = paste0("dmr_", prefix2, ".fdr.bed.gz")
if (file.exists(probes_file)) {
  probes = read.table(gzfile(probes_file), comment="@", header=TRUE);
} else {
  warning(paste0("probes_file ", probes_file, " does not exist. Have to fix it! "))
  return(NULL)    
}
head(probes)
dim(probes)
if (sum( paste0(bed_ewas[,1], ":", bed_ewas[,2], "-", bed_ewas[,3]) !=  paste0(probes[,1], ":", probes[,2], "-", probes[,3])) != 0) {
  stop("Error when namimg probes.")
}
rownames(probes) = rownames(bed_ewas)

regions_file = paste0("dmr_", prefix2, ".regions-t.bed"   )
if (file.exists(regions_file)) {
  regions = read.table(regions_file, comment="@", header=TRUE, stringsAsFactors=FALSE)
} else {
  warning(paste0("regions_file ", regions_file, " does not exist. Have to fix it! "))
  return(NULL)
}

rownames(regions) = paste0(regions[,1], ":", regions[,2], "-", regions[,3])
head(regions[ rev(order(regions$n_probes)),],50)
bed_regions = regions
bed_regions[,4] = paste0(bed_regions[,1], ":", bed_regions[,2], "-", bed_regions[,3])
bed_regions[,5] = bed_regions[,"z_sidak_p"]
bed_regions[,6] = "+"
bed_regions = bed_regions[,1:6]
colnames(bed_regions) = c("chr", "start", "end", "name", "pval", "strand")
head(bed_regions)
new_regions = regions[ rev(order(regions$n_probes)),]
new_regions

# Read comb-p ewas input
bed_ewas_var = read.table(bed_ewas_var_filename, sep="\t", header=TRUE)
rownames(bed_ewas_var) = bed_ewas_var$probes
head(bed_ewas_var)
dim(bed_ewas_var)

# Read comb-p outputs
probes_file_var = paste0("dmr_", prefix2_var, ".fdr.bed.gz")
if (file.exists(probes_file_var)) {
  probes_var = read.table(gzfile(probes_file_var), comment="@", header=TRUE);
} else {
  warning(paste0("probes_file_var ", probes_file_var, " does not exist. Have to fix it! "))
  return(NULL)    
}
head(probes_var)
dim(probes_var)
if (sum( paste0(bed_ewas_var[,1], ":", bed_ewas_var[,2], "-", bed_ewas_var[,3]) !=  paste0(probes_var[,1], ":", probes_var[,2], "-", probes_var[,3])) != 0) {
  stop("Error when namimg probes.")
}
rownames(probes_var) = rownames(bed_ewas_var)

regions_file_var = paste0("dmr_", prefix2_var, ".regions-t.bed"   )
if (file.exists(regions_file_var)) {
  regions_var = read.table(regions_file_var, comment="@", header=TRUE, stringsAsFactors=FALSE)
} else {
  warning(paste0("regions_file_var ", regions_file_var, " does not exist. Have to fix it! "))
  return(NULL)
}

rownames(regions_var) = paste0(regions_var[,1], ":", regions_var[,2], "-", regions_var[,3])
head(regions_var[ rev(order(regions_var$n_probes)),],50)
bed_regions_var = regions_var
bed_regions_var[,4] = paste0(bed_regions_var[,1], ":", bed_regions_var[,2], "-", bed_regions_var[,3])
bed_regions_var[,5] = bed_regions_var[,"z_sidak_p"]
bed_regions_var[,6] = "+"
bed_regions_var = bed_regions_var[,1:6]
colnames(bed_regions_var) = c("chr", "start", "end", "name", "pval", "strand")
head(bed_regions_var)
new_regions_var = regions_var[ rev(order(regions_var$n_probes)),]
new_regions_var

```

```{r}
DMR = apply_func(new_regions,1,function(l){
  chr = l[[1]]
  st = as.numeric(l[[2]])
  stop = as.numeric(l[[3]])
  r1 = subset(bed_ewas, chrom == chr & start >= st & end <= stop)
  ret = c(
      min_beta_C = min(r1$beta_C),
      max_beta_C = max(r1$beta_C),
      mean_beta_C = mean(r1$beta_C),
      min_beta_D = min(r1$beta_D),
      max_beta_D = max(r1$beta_D),
      mean_beta_D = mean(r1$beta_D)
  )
  return(ret)
})
DMR = t(DMR)
new_regions = cbind(new_regions,DMR)
head(new_regions)

# Viewing lm parameters
n_probes = readline(prompt = "Number of probes: ")
test = apply_func(d[1:n_probes,c(idx_C,idx_D)],1, function(l){
  #l = d[rownames(d)[1],]
  data = e[colnames(d),]
  data$meth = l
  m_DC = lm(meth~cond, data[c(idx_C,idx_D),])
  boxplot(meth~cond, data[c(idx_C,idx_D),])
  abline(h=mean(data[idx_C,3]), col=4)
  abline(h=mean(data[idx_D,3]), col=2)
  abline(h=m_DC$coef[[1]], lty=2)
  abline(h=m_DC$coef[[1]]+m_DC$coef[[2]], lty=3)
}
)

DMR_var = apply_func(new_regions_var, 1, function(l){
  #l = new_regions[1,]
  chr = l[[1]]
  st = as.numeric(l[[2]])
  stop = as.numeric(l[[3]])
  r1 = subset(bed_ewas_var, chrom == chr & start >= st & end <= stop)
  ret = c(
      min_beta = min(r1$beta_DC),
      max_beta = max(r1$beta_DC),
      mean_beta20 = mean(r1$beta_DC),
      NULL
  )
  return(ret)
})
DMR_var = t(DMR_var)
new_regions_var = cbind(new_regions_var,DMR_var)
new_regions_var = new_regions_var[ rev(order(new_regions_var$n_probes)),]
new_regions_var



```

# Plotting

## Plotting Comb-P correction of p-value

```{r plotting comb-p}
plot_combp_res = function (rois, ewas, combp_res_probes, legendplace="topright") {
  id_probes = ewas[as.character(ewas[,1])==as.character(rois[,1]) & ewas[,2]>=rois[,2] & ewas[,2]<=rois[,3],4]
  sub_ewas = ewas[ewas[,4]%in%id_probes, ]
  
  pval_ewas = combp_res_probes[paste0(combp_res_probes[,1], ":", combp_res_probes[,2]) %in% paste0(sub_ewas[,1], ":", sub_ewas[,2]),]$p
  pval_slk =  combp_res_probes[paste0(combp_res_probes[,1], ":", combp_res_probes[,2]) %in% paste0(sub_ewas[,1], ":", sub_ewas[,2]),]$region.p
  qval_slk =  combp_res_probes[paste0(combp_res_probes[,1], ":", combp_res_probes[,2]) %in% paste0(sub_ewas[,1], ":", sub_ewas[,2]),]$region.q 

  pval_ewas[pval_ewas==0] = 10^-45
  pval_slk [pval_slk ==0] = 10^-45
  qval_slk [qval_slk ==0] = 10^-45 

  # plot
  layout(matrix(c(2,1,1,1,1), 1))
  x = 1:length(-log10(pval_ewas))
  plot(x, -log10(pval_ewas), col="red", xaxt="n", 
    xlab="", ylab="-log10(p-values)",
    main=paste0(rois[[1]], ":", rois[[2]], ":", rois[[3]]),
    ylim=c(0, min(45, max(-log10(pval_slk), -log10(pval_ewas)))), 
    type="l", lty=3, lwd=2
  )
  axis(1, at=x, labels=sub_ewas$probes,las=2, cex.axis = 0.5, cex.axis = 0.5)
  lines(-log10(pval_slk), col="blue"  , type="l", lty=3, lwd=2)
  lines(-log10(qval_slk), col="purple", type="l", lty=3, lwd=2) 

  # # add Student pvals
  # if (length(gene_symbols)>1) {
  #   for (g in gene_symbols) {
  #     lines(sub_ewas[,paste0("lpval_student_", g)], col=pals::glasbey()[which(gene_symbols%in%g)], type="l")
  #   }
  # }
  # add DMR
  abline(h=-log10(as.numeric(pval_tresh)), col="black", lwd=2, lty=2)
  for (i in 1:nrow(combp_res_region)) {
    x1 = c(which(sub_ewas[,2] == combp_res_region[i,2]), which(sub_ewas[,3] == combp_res_region[i,3]))
    y1 = rep(-log10(as.numeric(pval_tresh)), length(x1))
    lines(x1,y1, type="o", col="green", pch=18, lwd=4)
  }
  # add legend
  col = c("red","blue", "purple", "black", "green")
  lwd = c(2,2,2,2,4)
  lty = c(3,3,3,2,1)
  legend=c("pval Fisher", "pval SLK", "qval SLK",  "threshold", "DMR")
  legend(legendplace, legend=legend, col=col, lwd=lwd, lty=lty)  
  par(mar=c(0,0,0,0), mgp=c(3, 1, 0), las=0)
  plot.new()
  par(mar=c(0,0,0,0), mgp=c(3, 1, 0), las=0)
  par(mar=c(5.1, 4.1, 4.1, 2.1), mgp=c(3, 1, 0), las=0)
  # if (length(gene_symbols)>1) {
  #   col   = c(pals::glasbey()[1:length(gene_symbols)])
  #   lwd   = c(rep(1, length(gene_symbols)))
  #   lty   = c(rep(1, length(gene_symbols)))
  #   legend= c(paste0("pval Student ", gene_symbols))
  #   legend("top", legend=legend, col=col, lwd=lwd, lty=lty, bty="n")
  # }
  par(mar=c(5.1, 4.1, 4.1, 2.1), mgp=c(3, 1, 0), las=0)
  # return(mdata)
}

plot_combp_res_var = function (rois_var, ewas_var, combp_res_probes_var, legendplace="topright") {
  id_probes = ewas_var[as.character(ewas_var[,1])==as.character(rois_var[,1]) & ewas_var[,2]>=rois_var[,2] & ewas_var[,2]<=rois_var[,3],4]
  sub_ewas = ewas_var[ewas_var[,4]%in%id_probes, ]
  
  pval_ewas = combp_res_probes_var[paste0(combp_res_probes_var[,1], ":", combp_res_probes_var[,2]) %in% paste0(sub_ewas[,1], ":", sub_ewas[,2]),]$p
  pval_slk =  combp_res_probes_var[paste0(combp_res_probes_var[,1], ":", combp_res_probes_var[,2]) %in% paste0(sub_ewas[,1], ":", sub_ewas[,2]),]$region.p
  qval_slk =  combp_res_probes_var[paste0(combp_res_probes_var[,1], ":", combp_res_probes_var[,2]) %in% paste0(sub_ewas[,1], ":", sub_ewas[,2]),]$region.q 

  pval_ewas[pval_ewas==0] = 10^-45
  pval_slk [pval_slk ==0] = 10^-45
  qval_slk [qval_slk ==0] = 10^-45 

  # plot
  layout(matrix(c(2,1,1,1,1), 1))
  x = 1:length(-log10(pval_ewas))
  plot(x, -log10(pval_ewas), col="red", xaxt="n", 
    xlab="", ylab="-log10(p-values)",
    main=paste0(rois_var[[1]], ":", rois_var[[2]], ":", rois_var[[3]]),
    ylim=c(0, min(45, max(-log10(pval_slk), -log10(pval_ewas)))), 
    type="l", lty=3, lwd=2
  )
  axis(1, at=x, labels=sub_ewas$probes,las=2, cex.axis = 0.5, cex.axis = 0.5)
  lines(-log10(pval_slk), col="blue"  , type="l", lty=3, lwd=2)
  lines(-log10(qval_slk), col="purple", type="l", lty=3, lwd=2) 

  # # add Student pvals
  # if (length(gene_symbols)>1) {
  #   for (g in gene_symbols) {
  #     lines(sub_ewas[,paste0("lpval_student_", g)], col=pals::glasbey()[which(gene_symbols%in%g)], type="l")
  #   }
  # }
  # add DMR
  abline(h=-log10(as.numeric(pval_tresh_var)), col="black", lwd=2, lty=2)
  for (i in 1:nrow(combp_res_region_var)) {
    x1 = c(which(sub_ewas[,2] == combp_res_region_var[i,2]), which(sub_ewas[,3] == combp_res_region_var[i,3]))
    y1 = rep(-log10(as.numeric(pval_tresh_var)), length(x1))
    lines(x1,y1, type="o", col="green", pch=18, lwd=4)
  }
  # add legend
  col = c("red","blue", "purple", "black", "green")
  lwd = c(1,1,1,1,4)
  lty = c(3,3,3,2,1)
  legend=c("pval Fisher", "pval SLK", "qval SLK",  "threshold", "DMR")
  legend(legendplace, legend=legend, col=col, lwd=lwd, lty=lty)  
  par(mar=c(0,0,0,0), mgp=c(3, 1, 0), las=0)
  plot.new()
  par(mar=c(0,0,0,0), mgp=c(3, 1, 0), las=0)
  par(mar=c(5.1, 4.1, 4.1, 2.1), mgp=c(3, 1, 0), las=0)
  # if (length(gene_symbols)>1) {
  #   col   = c(pals::glasbey()[1:length(gene_symbols)])
  #   lwd   = c(rep(1, length(gene_symbols)))
  #   lty   = c(rep(1, length(gene_symbols)))
  #   legend= c(paste0("pval Student ", gene_symbols))
  #   legend("top", legend=legend, col=col, lwd=lwd, lty=lty, bty="n")
  # }
  par(mar=c(5.1, 4.1, 4.1, 2.1), mgp=c(3, 1, 0), las=0)
  # return(mdata)
}

# reading combp outputs
## Mean outputs
ewas = read.table(paste0("ewas4combp_", prefix, ".bed"), comment="@",header=TRUE) 
combp_res_probes = read.table(gzfile(paste0("dmr_", prefix2, ".fdr.bed.gz")), comment="@", header=TRUE)
combp_res_region = read.table(paste0("dmr_", prefix2, ".regions-t.bed"), comment="@", header=TRUE)

## Variance outputs
ewas_var = read.table(paste0("ewas4combp_", prefix_var, ".bed"), comment="@",header=TRUE) ## variance outputs (V)
combp_res_probes_var = read.table(gzfile(paste0("dmr_", prefix2_var, ".fdr.bed.gz")), comment="@", header=TRUE)
combp_res_region_var = read.table(paste0("dmr_", prefix2_var, ".regions-t.bed"), comment="@", header=TRUE)

# select region of interest
## Mean outputs
rois = combp_res_region[order(-combp_res_region$n_probes, combp_res_region$z_sidak_p),]

##Variance outputs
rois_var = combp_res_region_var[order(-combp_res_region_var$n_probes, combp_res_region_var$z_sidak_p),]

# plot them
## for the mean
for (i in 1:min(6, nrow(rois))) {
  plot_combp_res(rois[i,], ewas, combp_res_probes)
}

## for the variance
for (i in 1:min(6, nrow(rois_var))) {
  plot_combp_res_var(rois_var[i,], ewas_var, combp_res_probes_var)
}


```

## Plotting DMRs

```{r}
# plotting mean DMRs
mean_plot = apply_func(new_regions, 1, function(l){
  #l = new_regions[1,]
  chr = l[[1]]
  st = as.numeric(l[[2]])
  stop = as.numeric(l[[3]])
  r1 = subset(bed_ewas, chrom == chr & start >= st & end <= stop)
  #print(r1)
  df = melt(bed_ewas[rownames(r1),], id.vars=colnames(bed_ewas))
  replicates = c("C1","C2","C3","C4","C5","C6","C7","C8","D1","D2","D3","D4","D5","D6","D7","D8")
  df=df[,c("start", "probes","beta_C","beta_D","sd_C","sd_D",replicates)]
  df= pivot_longer(df,cols=7:22, names_to="condition",values_to="meth_value")
  df = pivot_longer(df, cols=c("beta_C", "beta_D"), names_to="mean", values_to = "mean_value")
  df = pivot_longer(df, cols=c("sd_C", "sd_D"), names_to="sd", values_to = "sd_value")
  df$cond=substr(df$mean, 6, 6)
  df = df[order(df$cond),]
  df = data.frame(df)
  cd_C = df[substr(df[,colnames(df)=="condition"],1,1)=="C"&df$cond=="C"&df$mean=="beta_C"&df$sd=="sd_C",]
  cd_D = df[substr(df[,colnames(df)=="condition"],1,1)=="D"&df$cond=="D"&df$mean=="beta_D"&df$sd=="sd_D",]
  concat = rbind(cd_C,cd_D)
  boxplot(meth_value~cond+start,concat,las=2,border=c(2,4))
  boxplot(meth_value~cond+start,concat,las=2,border=c(2,4),ylim=c(0,1))
  #points(concat$mean_value[concat$cond=="C"],pch=19, col=2)
  #points(concat$mean_value[concat$cond=="D"],pch=19, col=4)
  
  # df = data.frame(df)
  # for (i in 1:nrow(df)){
  #   if(!is.na(df[i,])){
  #     m_cond = unlist(strsplit(df[i,colnames(df)=="mean"],"_"))
  #     s_cond = unlist(strsplit(df[i,colnames(df)=="sd"],"_"))
  #     if(m_cond[[2]]!=s_cond[[2]]){
  #       df=df[-i,]
  #     }
  #   }
  #   }
  # df = distinct(df,start,sd,.keep_all = T)
  # print(df)
  p1 = ggplot(concat, aes(x=start, y=mean_value, color=cond)) + geom_point() + geom_errorbar(aes(ymin=mean_value-sd_value, ymax=mean_value+sd_value))
  print(p1)
})

# plotting var DMRs
var_plot = apply_func(new_regions_var, 1, function(l){
  #l = new_regions_var[7,]
  chr = l[[1]]
  st = as.numeric(l[[2]])
  stop = as.numeric(l[[3]])
  r1 = subset(bed_ewas, chrom == chr & start >= st & end <= stop)
  #print(r1)
  df = melt(bed_ewas[rownames(r1),], id.vars=colnames(bed_ewas))
  df=df[,c("start", "probes","beta_C","beta_D","sd_C","sd_D",replicates)]
  df= pivot_longer(df,cols=7:22, names_to="condition",values_to="meth_value")
  df = pivot_longer(df, cols=c("beta_C", "beta_D"), names_to="mean", values_to = "mean_value")
  df = pivot_longer(df, cols=c("sd_C", "sd_D"), names_to="sd", values_to = "sd_value")
  df$cond=substr(df$mean, 6, 6)
  df = df[order(df$cond),]
  df = data.frame(df)
  cd_C = df[substr(df[,colnames(df)=="condition"],1,1)=="C"&df$cond=="C"&df$mean=="beta_C"&df$sd=="sd_C",]
  cd_D = df[substr(df[,colnames(df)=="condition"],1,1)=="D"&df$cond=="D"&df$mean=="beta_D"&df$sd=="sd_D",]
  concat = rbind(cd_C,cd_D)
  boxplot(meth_value~cond+start,concat,las=2,border=c(2,4))
  boxplot(meth_value~cond+start,concat,las=2,border=c(2,4),ylim=c(0,1))
  #points(concat$mean_value[concat$cond=="C"],pch=19, col=2)
  #points(concat$mean_value[concat$cond=="D"],pch=19, col=4)
  p2 = ggplot(concat, aes(x=start, y=mean_value, color=cond)) + geom_point() + geom_errorbar(aes(ymin=mean_value-sd_value, ymax=mean_value+sd_value))
  print(p2)

})
```

# PCA

```{r fig.width=9, fig.height=9, eval=TRUE, label="PCA"}
if (!exists("pca")) {
  dt = s$data
  dim(dt)
  # filtering...
  idx = apply(is.na(dt), 1, any)
  sum(idx)
  dt = dt[!idx,]
  idx = apply(dt, 1, function (l){
    length(unique(l)) == 1
  })
  sum(idx)
  dt = dt[!idx,]
  dim(dt)
  set.seed(1)
  pca = prcomp(t(dt[sample(1:nrow(dt), 1000),]), scale=TRUE)  
}
  
v = pca$sdev * pca$sdev
p = v / sum(v) * 100
layout(matrix(1:4,2, byrow=FALSE), respect=TRUE)
barplot(p)
i=3
j=2
plot(pca$x[,i], pca$x[,j], xlab=paste0("PC", i, "(", signif(p[i], 3), "%)"), ylab=paste0("PC", j, "(", signif(p[j], 3), "%)"), col=as.numeric(s$exp_grp[rownames(pca$x),]$cond), pch=16)
text(pca$x[,i], pca$x[,j], rownames(pca$x))
i=1
j=3
plot(pca$x[,i], pca$x[,j], xlab=paste0("PC", i, "(", signif(p[i], 3), "%)"), ylab=paste0("PC", j, "(", signif(p[j], 3), "%)"), col=as.numeric(s$exp_grp[rownames(pca$x),]$cond), pch=16)
text(pca$x[,i], pca$x[,j], rownames(pca$x))
i=1
j=2
plot(pca$x[,i], pca$x[,j], xlab=paste0("PC", i, "(", signif(p[i], 3), "%)"), ylab=paste0("PC", j, "(", signif(p[j], 3), "%)"), col=as.numeric(s$exp_grp[rownames(pca$x),]$cond), pch=16)
text(pca$x[,i], pca$x[,j], rownames(pca$x))
```
```{r}
for (i in 1:ncol(d[,idx_C])){
  plot(density(na.omit(d[,i])),xlab="sample in C", main="Density")
}
for (i in 1:ncol(d[,idx_D])){
  plot(density(na.omit(d[,i])),xlab="sample in D", main="Density")
}

```

# Session Information

```{r results="verbatim"}
sessionInfo()
```
